<a href="https://colab.research.google.com/github/lokinegalur/ML/blob/main/Feature_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler,Normalizer
arr=[[10,100,1000],[20,229,1212],[13,123,999],[99,889,3333]]
arr=np.array(arr)
print(arr)

[[  10  100 1000]
 [  20  229 1212]
 [  13  123  999]
 [  99  889 3333]]


In [ ]:
#MinMaxScaling
minmax_scaler=MinMaxScaler()
minmax_scaler.fit(arr)
minmax_scaler.transform(arr)

array([[0.00000000e+00, 0.00000000e+00, 4.28449015e-04],
       [1.12359551e-01, 1.63498099e-01, 9.12596401e-02],
       [3.37078652e-02, 2.91508238e-02, 0.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00]])

In [ ]:
#StandardScaling
std_scaler=StandardScaler()
std_scaler.fit(arr)
std_arr=std_scaler.transform(arr)
print(round(std_arr.mean())
print(std_arr.std())

5.551115123125783e-17
1.0


In [ ]:
#Normalize
normalizer=Normalizer()
normalizer.fit(arr)
normalizer.transform(arr)

array([[0.00994988, 0.09949879, 0.99498793],
       [0.01621263, 0.18563456, 0.98248509],
       [0.01291441, 0.12219018, 0.99242268],
       [0.02868781, 0.25761071, 0.96582283]])