<a href="https://colab.research.google.com/github/lokinegalur/ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
from time import process_time
python_list=[i for i in range(100000000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
total_time=process_time()-start_time
print(total_time)

10.485402793999999


In [11]:
np_array=np.array([i for i in range(100000000)])
start_time=process_time()
np_array+=5
total_time=process_time()-start_time
print(total_time)

0.0838528519999997


Numpy arrays

In [13]:
#list
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [14]:
#numpy array
np_array=np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


shape attribute of a numpy array

In [19]:
np_array=np.array([1,2,3,4,5])
print(np_array.shape)
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)


# Initial palceholders for arrays

In [26]:
#initialize array of zeros
x=np.zeros((4,5))
print(x,x.dtype)
y=np.ones((3,3))
print(y,y.dtype)     #dtype data type of each element of the array
z=np.full((5,5),6)
print(z,z.dtype)
print(type(x),type(y),type(z))   #type of the array

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] float64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]] int64
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [28]:
#creating identity matrix
identity=np.eye(5,dtype=int)
print(identity)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [33]:
#creating array with random values
#random float values between 0 to 1
a=np.random.random((4,5))
print(a)
#creating int values between range
b=np.random.randint(10,101,(3,4))
print(b)

[[0.7594584  0.15698592 0.38343167 0.45135865 0.6743021 ]
 [0.15578312 0.36832552 0.85505133 0.03193874 0.82657705]
 [0.40576598 0.52289217 0.81947104 0.09178756 0.01773828]
 [0.90706559 0.08749791 0.06783432 0.34606334 0.25171235]]
[[44 73 67 85]
 [18 99 40 43]
 [29 98 18 36]]


In [38]:
#array of evenly spaced values (from,to,no. of values)
c=np.linspace(5,50,5)  #(from , to , number of elements)
print(c)
#array of (from,to,step)
e=np.arange(10,30,5)
print(e)

[ 5.   16.25 27.5  38.75 50.  ]
[10 15 20 25]


In [39]:
#convert list to numpy array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(type(np_array))
np_array=np.array([1,2,3])
print(type(np_array))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Numpy array attributes

In [44]:
c=np.random.randint(5,90,(5,5),dtype=int)
print(c)
#array dimensions
print(c.shape)
#no. of dimensions
print(c.ndim)
#no. of elements
print(c.size)
#datatype of each value
print(c.dtype)

[[12 64 23 85 86]
 [89  6 44 17 86]
 [51 64 36 69 38]
 [77 30 55 17 83]
 [80 24 15 58 33]]
(5, 5)
2
25
int64


# Mathematical operations on the array

In [54]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)    #concatenation occurs for lists
a=np.random.randint(0,10,(4,4))
b=np.random.randint(10,20,(4,4))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
#operations using np module methods
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[1 0 6 4]
 [3 4 0 5]
 [1 5 9 8]
 [4 1 0 4]]
[[14 13 16 13]
 [10 15 13 12]
 [16 14 11 18]
 [19 17 12 13]]
[[15 13 22 17]
 [13 19 13 17]
 [17 19 20 26]
 [23 18 12 17]]
[[-13 -13 -10  -9]
 [ -7 -11 -13  -7]
 [-15  -9  -2 -10]
 [-15 -16 -12  -9]]
[[ 14   0  96  52]
 [ 30  60   0  60]
 [ 16  70  99 144]
 [ 76  17   0  52]]
[[0.07142857 0.         0.375      0.30769231]
 [0.3        0.26666667 0.         0.41666667]
 [0.0625     0.35714286 0.81818182 0.44444444]
 [0.21052632 0.05882353 0.         0.30769231]]
[[15 13 22 17]
 [13 19 13 17]
 [17 19 20 26]
 [23 18 12 17]]
[[-13 -13 -10  -9]
 [ -7 -11 -13  -7]
 [-15  -9  -2 -10]
 [-15 -16 -12  -9]]
[[ 14   0  96  52]
 [ 30  60   0  60]
 [ 16  70  99 144]
 [ 76  17   0  52]]
[[0.07142857 0.         0.375      0.30769231]
 [0.3        0.26666667 0.         0.41666667]
 [0.0625     0.35714286 0.81818182 0.44444444]
 [0.21052632 0.05882353 0.         0.30769231]]


# Array Manipulation

In [63]:
array=np.random.randint(0,5,(2,3))
print(array)
print(array.shape)
#transpose of array
#method1
trans=np.transpose(array)
print(trans)
print(trans.shape)
#method2
trans2=array.T  #T attribute corresponds to Transpose of array
print(trans2)

[[1 2 4]
 [4 0 0]]
(2, 3)
[[1 4]
 [2 0]
 [4 0]]
(3, 2)
[[1 4]
 [2 0]
 [4 0]]


In [68]:
#Reshaping the array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)
b=a.reshape((3,2))
print(b)

[[5 8 2]
 [9 3 2]]
(2, 3)
[[5 8]
 [2 9]
 [3 2]]
