<a href="https://colab.research.google.com/github/lokinegalur/ML/blob/main/numpyBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
#creating a 2-d numpy array
a = np.array([[4,5,6],[1,2,3]])

In [10]:
#dimension of numpy array
print(a.ndim)

2


In [11]:
#byte size of each element
print(a.itemsize)

8


In [12]:
#data type of each element
print(a.dtype)

int64


In [13]:
#size of the array
print(a.size)

6


In [20]:
#shape of array
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [23]:
#reshape the array
print(a)
a=a.reshape((1,6))      #for reshaping the rBefore*cBefore = rAfter*cAfter i.e no.of elements must be same in both cases
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [34]:
#1-d array slicing
a = np.array([1,2,3,4,5,6])
print(a[:])            #prints [0:n-1]
print(a[1:])           #prints [1:n-1]
print(a[2:4])          #prints starting from (2) (4-2) elements i.e elements at (2,3) index
print(a[1:1])          #doesn't print any elements
print(a[-1])
print(a[-2])

[1 2 3 4 5 6]
[2 3 4 5 6]
[3 4]
[]
6
5


In [45]:
#2-d array slicing
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#print 0th column
print(a[:,0])
#print 1st column
print(a[:,1])
#print 2nd colmn
print(a[:,2])
#print all row and 0th and 1st column
print(a[:,0:2])
#print 1st row all elements
print(a[0,:])
#print 2nd row 1st 3 columns
print(a[1,:3])

[1 6]
[2 7]
[3 8]
[[1 2]
 [6 7]]
[1 2 3 4 5]
[6 7 8]


In [49]:
#max min sum
print(a.max())
print(a.min())
print(a.sum())

10
1
55


In [50]:
#sum of all row and sum of all rows
print(a.sum(axis=0))     #for col
print(a.sum(axis=1))     #for row

[ 7  9 11 13 15]
[15 40]


In [51]:
#sqrt of each element
print(np.sqrt(a))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]


In [57]:
#standard deviation/mean/mode/abs
print(np.std(a))
print(np.mean(a))
print(np.median(a))
print(np.abs(a))

2.8722813232690143
5.5
5.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
#array addition,subtraction and multiplication
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]


In [67]:
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
